### ISSUE TITLE
Rain water problem

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/Python#1]
## Question:
Given an array of N non-negative integers - where each element in the array is a number of blocks in a pillar. Assume height and width of each block is 1, and calculate how much rainwater can accumulate between the pillars.
## Example-1:
` input : `
n = 6        
arr[]={3,0,2,0,4}
` output : `
7
![](<https://media.geeksforgeeks.org/wp-content/uploads/20200429012756/Untitled-Diagram821.png>)
## Example-2:
` input : `
n = 3
arr[] = {6,6,9}
` output : `
0
` Explanation : `
No water will be trapped
## Rules : 
- Don't ctrl+c and ctrl+v from the internet
- Code in ` python `
- Modify the https://github.com/KanailalManna/Python/blob/main/CollegePythonLab/Rain_water_trapped.py file

**Comment by abhishak3** [comment]
I would like to solve this problem. Can I have this issue?

**Comment by Kanai2003** [comment]
Okey

**Comment by Saurabhk1975** [comment]
please assign me this problem @KanailalManna

**Comment by Faizan96322** [comment]
hey @KanailalManna please assign me this task if @abhishak3 is not working on it!...I would like to contribute to this issue!

**Comment by Kanai2003** [comment]
I'm assigning you both @Faizan96322 @Saurabhk1975

**Comment by Kanai2003** [comment]
Time complexity should be O(n)
