### ISSUE TITLE
Sum of triplet

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/Python#2]
## Question :
Given a list of size N and an integer, M. Find if there's a triplet in the array which sums up to the given integer M.
## Instructions:
Time complexity : O(N^2)
Auxiliary space : O(1)
## Example:
` Input : `
N = 6
M= 13
arr[] = {1,4,45,6,10,8}
` Output : `
1
` Explanation : `
The triplet {1,4,8} in the array sums up to 13
## Rules: 
- Warning!!! :  don't ctrl+c and ctrl+v code from the internet
- code in ` python `
- Modify the  https://github.com/KanailalManna/Python/blob/main/CollegePythonLab/Sum_Of_Triplet.py   file 
- Comment below if you want to be assigned to this issue (then start working on the issue)

**Comment by ghost** [comment]
I want to contribute. So please assign me this issue.

**Comment by Kanai2003** [comment]
Okey, I'm assigning you but complete within 72 hrs.

**Comment by Abhishek-Vaidya** [comment]
I am willing to contribute to this issue
So can you please assign me this issue?

**Comment by Kanai2003** [comment]
ok

**Comment by Faizan96322** [comment]
hey, can you please assign me this issue if @TSLizard and @Abhishek-Vaidya is not working on it anymore!

**Comment by Abhishek-Vaidya** [comment]
I have solved the issue and done the pull request please check it.
