### ISSUE TITLE
Indian Flag

### ISSUE THREAD

**Issue by Kanai2003** [KanailalManna/Python#4]
## Instructions:
- Use the turtle library
- Don't ctrl+c and ctrl+v from the internet
- Modify the https://github.com/KanailalManna/Python/blob/main/CodeForFunOnly/IndianFlag.py file

**Comment by SaranshBaniyal** [comment]
Hey @KanailalManna I would like to contribute to this, please assign me this issue

**Comment by SubiditaB** [comment]
please assign me this issue

**Comment by Abhishek3223** [comment]
Please assign this isuse to me
